# -*- coding: utf-8 -*-
"""estudo de limite de segurança

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Juogi6dt3MgSSAFbYn1tYGq3QWCYMmBI
"""

limite_segurança = int(input("valor de segurança: "))
print()
print("-"* 50)
Venda_1 = int(input("primeira venda: "))
Venda_2 = int(input("segunda venda: "))
Venda_3 = int(input("terceira venda: "))
print()
print("-"* 50)
analisar_vendas = (Venda_1 + Venda_2 + Venda_3)
print("Valor total de vendas: ", analisar_vendas)
media = (analisar_vendas / 3)
print()
print("Valor da media de vendas: ", media)
print()
print("-"* 50)
if media <= limite_segurança:
  print("Valor seguro")
else:
  print("Valor não seguro")